import {
  Brain,
  Mic,
  BarChart3,
  MessageSquare,
  ShieldCheck,
  Trophy,
} from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI Mock Interviews",
    description:
      "Practice realistic HR and technical interviews generated by AI.",
  },
  {
    icon: Mic,
    title: "Speech Analysis",
    description:
      "Analyze confidence, filler words, pace, pronunciation, and fluency.",
  },
  {
    icon: BarChart3,
    title: "Performance Analytics",
    description:
      "Track interview scores, strengths, weaknesses, and overall progress.",
  },
  {
    icon: MessageSquare,
    title: "Instant AI Feedback",
    description:
      "Receive detailed suggestions after every interview session.",
  },
  {
    icon: ShieldCheck,
    title: "Industry-Based Questions",
    description:
      "Practice questions tailored for software engineering, HR, and more.",
  },
  {
    icon: Trophy,
    title: "Skill Improvement",
    description:
      "Improve communication, confidence, and interview readiness over time.",
  },
];

const Features = () => {
  return (
    <section
      id="features"
      className="py-24 bg-gray-50"
    >
      <div className="max-w-7xl mx-auto px-6">

        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-gray-900">
            Everything You Need To Ace Interviews
          </h2>

          <p className="mt-5 text-lg text-gray-600 max-w-3xl mx-auto">
            VerbaAI combines Artificial Intelligence, speech analytics,
            interview simulations, and performance tracking to help you become
            interview-ready.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature) => {
            const Icon = feature.icon;

            return (
              <div
                key={feature.title}
                className="bg-white rounded-2xl p-8 shadow-md hover:shadow-xl transition duration-300 hover:-translate-y-2"
              >
                <div className="w-14 h-14 rounded-xl bg-indigo-100 flex items-center justify-center mb-6">
                  <Icon className="w-7 h-7 text-indigo-600" />
                </div>

                <h3 className="text-xl font-semibold mb-3">
                  {feature.title}
                </h3>

                <p className="text-gray-600 leading-7">
                  {feature.description}
                </p>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};

export default Features;