import { ResumeReport } from "./types";

function section(title: string, items: string[]) {
  if (items.length === 0) return "";
  return `${title.toUpperCase()}\n${"-".repeat(title.length)}\n${items.map((i) => `- ${i}`).join("\n")}\n\n`;
}

export function formatReportAsText(report: ResumeReport): string {
  const date = new Date(report.createdAt).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let text = `PrepPilot AI Resume Report\n`;
  text += `${"=".repeat(22)}\n\n`;
  text += `File: ${report.fileName}\n`;
  text += `Analyzed: ${date}\n`;
  text += `ATS Score: ${report.atsScore}/100\n\n`;

  if (report.professionalSummary) {
    text += `PROFESSIONAL SUMMARY\n--------------------\n${report.professionalSummary}\n\n`;
  }

  text += section("Strengths", report.strengths);
  text += section("Weaknesses", report.weaknesses);
  text += section("Missing Keywords", report.missingKeywords);
  text += section("Grammar Issues", report.grammarIssues);
  text += section("Formatting Suggestions", report.formattingSuggestions);
  text += section("Suggestions", report.suggestions);

  text += `Generated by PrepPilot AI\n`;
  return text.trim() + "\n";
}
